main:
	@echo "Compilando ficheros..."
	g++ -std=c++20 main.cc src/multiplicacion/multiplicacion.cc tools/tools.cc -o multiplicacion

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f multiplicacion